-- Объединённая схема из Flyway-миграций V001-V009 data-sync-svc.
-- Используется в интеграционных тестах analytics-api (testcontainers).

CREATE TABLE statuses
(
    id     INTEGER PRIMARY KEY,
    status VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX idx_statuses_status ON statuses (status);

CREATE TABLE circuits
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref      VARCHAR(50)  NOT NULL,
    name     VARCHAR(100) NOT NULL,
    locality VARCHAR(100),
    country  VARCHAR(100)
);

CREATE UNIQUE INDEX idx_circuits_ref ON circuits (ref);

CREATE TABLE constructors
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref         VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    nationality VARCHAR(50)
);

CREATE UNIQUE INDEX idx_constructors_ref ON constructors (ref);

CREATE TABLE drivers
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref         VARCHAR(50) NOT NULL,
    number      INTEGER,
    code        VARCHAR(3),
    forename    VARCHAR(50) NOT NULL,
    surname     VARCHAR(50) NOT NULL,
    dob         DATE,
    nationality VARCHAR(50)
);

CREATE UNIQUE INDEX idx_drivers_ref ON drivers (ref);
CREATE INDEX idx_drivers_nationality ON drivers (nationality);

CREATE TABLE races
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season     INTEGER      NOT NULL,
    round      INTEGER      NOT NULL,
    circuit_id INTEGER      NOT NULL,
    name       VARCHAR(100) NOT NULL,
    date       DATE         NOT NULL,
    time       TIME,

    CONSTRAINT fk_races_circuit FOREIGN KEY (circuit_id)
        REFERENCES circuits (id),

    CONSTRAINT uk_races_season_round
        UNIQUE (season, round)
);

CREATE INDEX idx_races_season ON races (season);
CREATE INDEX idx_races_circuit_id ON races (circuit_id);
CREATE INDEX idx_races_date ON races (date);

CREATE TABLE results
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id           INTEGER       NOT NULL,
    driver_id         INTEGER       NOT NULL,
    constructor_id    INTEGER       NOT NULL,
    number            INTEGER,
    grid              INTEGER       NOT NULL,
    position          INTEGER,
    position_text     VARCHAR(3)    NOT NULL,
    position_order    INTEGER       NOT NULL,
    points            DECIMAL(5, 2) NOT NULL,
    laps              INTEGER       NOT NULL,
    time              VARCHAR(20),
    milliseconds      BIGINT,
    fastest_lap       INTEGER,
    fastest_lap_rank  INTEGER,
    fastest_lap_time  VARCHAR(20),
    fastest_lap_speed DECIMAL(7, 3),
    status_id         INTEGER       NOT NULL,

    CONSTRAINT fk_results_race
        FOREIGN KEY (race_id) REFERENCES races (id),

    CONSTRAINT fk_results_driver
        FOREIGN KEY (driver_id) REFERENCES drivers (id),

    CONSTRAINT fk_results_constructor
        FOREIGN KEY (constructor_id) REFERENCES constructors (id),

    CONSTRAINT fk_results_status
        FOREIGN KEY (status_id) REFERENCES statuses (id),

    CONSTRAINT uk_results_race_driver_position_order
        UNIQUE (race_id, driver_id, position_order)
);

CREATE INDEX idx_results_driver_id ON results (driver_id);
CREATE INDEX idx_results_constructor_id ON results (constructor_id);
CREATE INDEX idx_results_race_id ON results (race_id);
CREATE INDEX idx_results_position ON results (position) WHERE position IS NOT NULL;
CREATE INDEX idx_results_points ON results (points) WHERE points > 0;

CREATE TABLE qualifying
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id        INTEGER NOT NULL,
    driver_id      INTEGER NOT NULL,
    constructor_id INTEGER NOT NULL,
    number         INTEGER,
    position       INTEGER NOT NULL,
    q1             VARCHAR(20),
    q2             VARCHAR(20),
    q3             VARCHAR(20),

    CONSTRAINT fk_qualifying_race
        FOREIGN KEY (race_id) REFERENCES races (id),

    CONSTRAINT fk_qualifying_driver
        FOREIGN KEY (driver_id) REFERENCES drivers (id),

    CONSTRAINT fk_qualifying_constructor
        FOREIGN KEY (constructor_id) REFERENCES constructors (id),

    CONSTRAINT uk_qualifying_race_driver
        UNIQUE (race_id, driver_id)
);

CREATE INDEX idx_qualifying_driver_id ON qualifying (driver_id);
CREATE INDEX idx_qualifying_race_id ON qualifying (race_id);
CREATE INDEX idx_qualifying_position ON qualifying (position);

CREATE TABLE driver_standings
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id       INTEGER       NOT NULL,
    driver_id     INTEGER       NOT NULL,
    points        DECIMAL(6, 2) NOT NULL,
    position      INTEGER,
    position_text VARCHAR(3)    NOT NULL,
    wins          INTEGER       NOT NULL,

    CONSTRAINT fk_driver_standings_race
        FOREIGN KEY (race_id) REFERENCES races (id),

    CONSTRAINT fk_driver_standings_driver
        FOREIGN KEY (driver_id) REFERENCES drivers (id),

    CONSTRAINT uk_driver_standings_race_driver
        UNIQUE (race_id, driver_id)
);

CREATE INDEX idx_driver_standings_driver_id ON driver_standings (driver_id);
CREATE INDEX idx_driver_standings_race_id ON driver_standings (race_id);
CREATE INDEX idx_driver_standings_position ON driver_standings (position);

CREATE TABLE constructor_standings
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id        INTEGER       NOT NULL,
    constructor_id INTEGER       NOT NULL,
    points         DECIMAL(6, 2) NOT NULL,
    position       INTEGER,
    position_text  VARCHAR(3)    NOT NULL,
    wins           INTEGER       NOT NULL,

    CONSTRAINT fk_constructor_standings_race
        FOREIGN KEY (race_id) REFERENCES races (id),

    CONSTRAINT fk_constructor_standings_constructor
        FOREIGN KEY (constructor_id) REFERENCES constructors (id),

    CONSTRAINT uk_constructor_standings_race_constructor
        UNIQUE (race_id, constructor_id)
);

CREATE INDEX idx_constructor_standings_constructor_id ON constructor_standings (constructor_id);
CREATE INDEX idx_constructor_standings_race_id ON constructor_standings (race_id);
