spring:
  datasource:
    hikari:
      maximum-pool-size: 5

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false

sync:
  schedule:
    incremental-cron: "0 */5 * * * *"
