CREATE TABLE sync_jobs
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    job_type        VARCHAR(20)              NOT NULL,
    status          VARCHAR(20)              NOT NULL,
    started_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at    TIMESTAMP WITH TIME ZONE,
    error_message   TEXT,
    total_requests  INTEGER                  NOT NULL,
    failed_requests INTEGER                  NOT NULL,

    CONSTRAINT chk_sync_jobs_type
        CHECK (job_type IN ('FULL', 'INCREMENTAL')),

    CONSTRAINT chk_sync_jobs_status
        CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'PAUSED'))
);

CREATE INDEX idx_sync_jobs_status ON sync_jobs (status);
CREATE INDEX idx_sync_jobs_started_at ON sync_jobs (started_at DESC);

COMMENT ON TABLE sync_jobs IS 'Metadata for data synchronization jobs';
COMMENT ON COLUMN sync_jobs.job_type IS 'FULL - complete data load, INCREMENTAL - new data only';
COMMENT ON COLUMN sync_jobs.status IS 'Current job status';
COMMENT ON COLUMN sync_jobs.total_requests IS 'Total HTTP requests made';
COMMENT ON COLUMN sync_jobs.failed_requests IS 'Failed requests count (after all retries)';
