CREATE TABLE sync_checkpoints
(
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    job_id         BIGINT      NOT NULL,
    entity_type    VARCHAR(30) NOT NULL,
    status         VARCHAR(20) NOT NULL,
    last_offset    INTEGER     NOT NULL,
    last_season    INTEGER,
    last_round     INTEGER,
    records_synced INTEGER     NOT NULL,
    started_at     TIMESTAMP WITH TIME ZONE,
    completed_at   TIMESTAMP WITH TIME ZONE,
    error_message  TEXT,
    retry_count    INTEGER     NOT NULL,

    CONSTRAINT fk_sync_checkpoints_job
        FOREIGN KEY (job_id) REFERENCES sync_jobs (id) ON DELETE CASCADE,

    CONSTRAINT uk_sync_checkpoints_job_entity
        UNIQUE (job_id, entity_type),

    CONSTRAINT chk_sync_checkpoints_entity_type
        CHECK (entity_type IN (
                               'STATUSES',
                               'CIRCUITS',
                               'CONSTRUCTORS',
                               'DRIVERS',
                               'RACES',
                               'RESULTS',
                               'QUALIFYING',
                               'DRIVER_STANDINGS',
                               'CONSTRUCTOR_STANDINGS'
            )),

    CONSTRAINT chk_sync_checkpoints_status
        CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED'))
);

CREATE INDEX idx_sync_checkpoints_job_id ON sync_checkpoints (job_id);
CREATE INDEX idx_sync_checkpoints_status ON sync_checkpoints (status);

COMMENT ON TABLE sync_checkpoints IS 'Checkpoints for resuming interrupted synchronization';
COMMENT ON COLUMN sync_checkpoints.entity_type IS 'Type of entity being synchronized';
COMMENT ON COLUMN sync_checkpoints.last_offset IS 'Pagination offset (for reference tables)';
COMMENT ON COLUMN sync_checkpoints.last_season IS 'Last successfully processed season';
COMMENT ON COLUMN sync_checkpoints.last_round IS 'Last successfully processed round within season';
COMMENT ON COLUMN sync_checkpoints.retry_count IS 'Number of retry attempts for this checkpoint';
